# Run the Guardener

name: Guarden my Dockerfile

# Manual run, provide group ID and desired tag at runtime
# Verify that the identity secret is added to the repository secrets before running
on:
  workflow_dispatch:
    secrets:
      GUARDENER_DEMO_CHAINCTL_IDENTITY:
        required: true
    inputs:
      NAMESPACE:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      GROUP:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: guardener-demo

jobs:
  # Run the Guardener to migrate the Dockerfile
  run-guardener:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repo
        uses: chainguard-actions/actions-checkout@59b7218bfc2eaabc464f1254f6e1dac5bda91d94 # v4

      - name: Setup chainctl
        uses: chainguard-dev/setup-chainctl@v0.5.1

      - name: Get GitHub OIDC token
        id: oidc
        shell: bash
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Run guardener on Dockerfile
        shell: bash
        run: |
          chainctl auth login \
            --identity "${{ secrets.GUARDENER_DEMO_CHAINCTL_IDENTITY }}" \
            --identity-token "${{ steps.oidc.outputs.token }}"

          chainctl agent dockerfile build -f Dockerfile -t myapp:cg \
            --group "${{ inputs.GROUP }}" \
            --non-interactive

      - name: Save migrated Dockerfile
        uses: chainguard-actions/actions-upload-artifact@61ae9717c37cd5ac5fcaa5599c0dab961d043ecc # v4.6.2
        with:
          name: Dockerfile.migrated
          path: ./Dockerfile.migrated
  
  # Build and push the migrated image to GitHub Container Registry
  build-and-push-image:
    needs: run-guardener
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out repo
        uses: chainguard-actions/actions-checkout@59b7218bfc2eaabc464f1254f6e1dac5bda91d94 # v4

      - name: 'Login to GitHub Container Registry'
        uses: chainguard-actions/docker-login-action@471f865b6525577aec1a207ce43d4ec3ed8a996d # v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Get GitHub OIDC token
        id: oidc
        shell: bash
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Setup chainctl
        uses: chainguard-dev/setup-chainctl@v0.5.1
      
      - name: Auth with chainctl using OIDC token
        shell: bash
        run: |
          chainctl auth login \
            --identity "${{ secrets.GUARDENER_DEMO_CHAINCTL_IDENTITY }}" \
            --identity-token "${{ steps.oidc.outputs.token }}"

      - name: Download migrated Dockerfile
        uses: chainguard-actions/actions-download-artifact@75db10217d80f4a4c7e15d54b2dd9adfc6c78f83 # v4.3.0
        with:
          name: Dockerfile.migrated
          path: ./artifacts

      - name: Build and push image with new Dockerfile
        run: |
          docker build . -f ./artifacts/Dockerfile.migrated -t ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          docker push ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}

      - name: Scan the image with Grype
        uses: chainguard-actions/anchore-scan-action@771570842dd6dc0aec4a74f6226a15e7178ae83d # v7.4.2
        with:
          image: ghcr.io/${{ inputs.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          fail-build: false
          output-format: json
          output-file: scan-results.json

      - name: Show Grype scan results
        run: |
          cat scan-results.json | jq '[.matches[] | {severity: .vulnerability.severity, id: .vulnerability.id, package: .artifact.name}]'